name: flutter_application_2_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0+1
  path: ^1.8.3
  flutter_map: ^6.0.0
  flutter_map_heatmap: ^0.0.7
  #flutter_local_notifications: any
  #shared_preferences: any # For storing user preferences
  latlong2: ^0.9.1  # For handling latitude/longitude
  permission_handler: ^11.0.0
  geolocator: ^10.0.0  # For getting user's current location
  http: ^1.3.0  # For making API requests
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: any
  js: ^0.6.3
  firebase_database: any
  firebase_storage: any
  flutter_dotenv: ^5.1.0
  flexible_polyline_dart: any
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_web_compilers: ^4.0.6
  

flutter:
  uses-material-design: true

  assets:
    - .env