// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5chS-Kxje0kqkUH2_bkN9p4VJzjpda3s',
    appId: '1:3170614288:web:103b712876d3fd011e9e95',
    messagingSenderId: '3170614288',
    projectId: 'test-project-firebase-001',
    authDomain: 'test-project-firebase-001.firebaseapp.com',
    storageBucket: 'test-project-firebase-001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLtT3752aOlYcarfrmr5s7JWnVqloocmQ',
    appId: '1:3170614288:android:2958479ea62a63881e9e95',
    messagingSenderId: '3170614288',
    projectId: 'test-project-firebase-001',
    storageBucket: 'test-project-firebase-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQCtakYXJVAZv5tqmw2OXa0lL0zb40Rlc',
    appId: '1:3170614288:ios:a896713e8e2906ef1e9e95',
    messagingSenderId: '3170614288',
    projectId: 'test-project-firebase-001',
    storageBucket: 'test-project-firebase-001.firebasestorage.app',
    iosBundleId: 'com.example.testApplicationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQCtakYXJVAZv5tqmw2OXa0lL0zb40Rlc',
    appId: '1:3170614288:ios:a896713e8e2906ef1e9e95',
    messagingSenderId: '3170614288',
    projectId: 'test-project-firebase-001',
    storageBucket: 'test-project-firebase-001.firebasestorage.app',
    iosBundleId: 'com.example.testApplicationFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5chS-Kxje0kqkUH2_bkN9p4VJzjpda3s',
    appId: '1:3170614288:web:f3d1b86ef8e995721e9e95',
    messagingSenderId: '3170614288',
    projectId: 'test-project-firebase-001',
    authDomain: 'test-project-firebase-001.firebaseapp.com',
    storageBucket: 'test-project-firebase-001.firebasestorage.app',
  );
}
